alias c='cd .. && pwd'
alias ..='cd ../.. && pwd'
alias ...='cd ../../.. && pwd'
alias ....='cd ../../../.. && pwd'
alias .....='cd ../../../../.. && pwd'
alias d='du -hs'
alias e='logout'
alias egrep='egrep --color=always'
alias f='fgrep --color=always'
alias g='ga; gcm; gp'
alias gca='git commit -a'
alias gcam='git commit -am'
#alias gp='git push https://username:password@github.com/username/repository.git master'
alias grep='grep --color=always'
alias h='history >> $HOME/.historyfile'
alias j='jobs'
alias i='whoami'
alias l='ls -alG'
alias lr='ls -alR'
alias ls='ls --color=always'
alias p='pwd'
alias pacman='pacman --color=always'
alias pcs='pacman -S --color=always'
alias pcss='pacman -Ss --color=always'
alias q='logout'
alias rf='rm -rf'
PATH=/root/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/root/.gem/ruby/2.5.0/bin
export GEM_HOME=/root/.gem
$HOME/./stkindai.sh